FROM --platform=$BUILDPLATFORM docker.io/golang:1.22@sha256:800fde66644c2447abc2a085cbecdcb53d2e21234ec8e80be0c90fc011a93f4b as build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/alpine:3.19@sha256:af4785ccdbcd5cde71bfd5b93eabd34250b98651f19fe218c91de6c8d10e21c5

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="drone-fork-approval"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/drone-fork-approval"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/drone-fork-approval"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/drone-fork-approval"

ARG TARGETOS
ARG TARGETARCH

RUN addgroup -g 1001 -S app && \
    adduser -S -D -H -u 1001 -s /sbin/nologin -G app -g app app

RUN apk --update add --no-cache ca-certificates && \
    apk upgrade --no-cache libcrypto3 libssl3 && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

COPY --from=build /src/dist/drone-fork-approval /bin/drone-fork-approval

EXPOSE 3000

USER app

ENTRYPOINT ["/bin/drone-fork-approval"]
CMD []
